<?php include('config.php'); 

$var="Diwali";
$query = "INSERT INTO `list`(`word`,`1`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="is";
$query = "INSERT INTO `list`(`word`,`1`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="a";
$query = "INSERT INTO `list`(`word`,`1`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="Hindu";
$query = "INSERT INTO `list`(`word`,`1`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="festival";
$query = "INSERT INTO `list`(`word`,`1`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="also";
$query = "INSERT INTO `list`(`word`,`1`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="celebrated";
$query = "INSERT INTO `list`(`word`,`1`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="by";
$query = "INSERT INTO `list`(`word`,`1`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="Jains";
$query = "INSERT INTO `list`(`word`,`1`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="Sikhs";
$query = "INSERT INTO `list`(`word`,`1`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="and";
$query = "INSERT INTO `list`(`word`,`1`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="Buddhists";
$query = "INSERT INTO `list`(`word`,`1`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `1`=2 WHERE `word`='Diwali';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `1`=2 WHERE `word`='is';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `1`=2 WHERE `word`='festival';";
mysqli_query($con,$query);
$var="of";
$query = "INSERT INTO `list`(`word`,`1`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="lights";
$query = "INSERT INTO `list`(`word`,`1`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `1`=2 WHERE `word`='and';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `1`=3 WHERE `word`='Diwali';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `1`=3 WHERE `word`='is';";
mysqli_query($con,$query);
$var="celebrated";
$query = "INSERT INTO `list`(`word`,`1`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="as";
$query = "INSERT INTO `list`(`word`,`1`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="reunion";
$query = "INSERT INTO `list`(`word`,`1`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="with";
$query = "INSERT INTO `list`(`word`,`1`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="friends";
$query = "INSERT INTO `list`(`word`,`1`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `1`=3 WHERE `word`='and';";
mysqli_query($con,$query);
$var="families";
$query = "INSERT INTO `list`(`word`,`1`)VALUES ('".$var."',1);";
mysqli_query($con,$query);


$query = "UPDATE `list` SET `2`=1 WHERE `word`='Diwali';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `2`=1 WHERE `word`='is';";
mysqli_query($con,$query);
$var="one";
$query = "INSERT INTO `list`(`word`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `2`=1 WHERE `word`='of';";
mysqli_query($con,$query);
$var="of";
$query = "INSERT INTO `list`(`word`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="the";
$query = "INSERT INTO `list`(`word`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="biggest";
$query = "INSERT INTO `list`(`word`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="celebrations";
$query = "INSERT INTO `list`(`word`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="in";
$query = "INSERT INTO `list`(`word`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="India";
$query = "INSERT INTO `list`(`word`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="It";
$query = "INSERT INTO `list`(`word`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `2`=2 WHERE `word`='is';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `2`=1 WHERE `word`='celebrated';";
mysqli_query($con,$query);
$var="as";
$query = "INSERT INTO `list`(`word`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="most";
$query = "INSERT INTO `list`(`word`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="loved";
$query = "INSERT INTO `list`(`word`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `2`=1 WHERE `word`='festival';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `2`=2 WHERE `word`='in';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `2`=2 WHERE `word`='India';";
mysqli_query($con,$query);


$var="We";
$query = "INSERT INTO `list`(`word`,`3`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="do";
$query = "INSERT INTO `list`(`word`,`3`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="lots";
$query = "INSERT INTO `list`(`word`,`3`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `3`=1 WHERE `word`='of';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `3`=1 WHERE `word`='Diwali';";
mysqli_query($con,$query);
$var="shopping";
$query = "INSERT INTO `list`(`word`,`3`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="on";
$query = "INSERT INTO `list`(`word`,`3`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="Dhanteras";
$query = "INSERT INTO `list`(`word`,`3`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `3`=2 WHERE `word`='on';";
mysqli_query($con,$query);
$var="this";
$query = "INSERT INTO `list`(`word`,`3`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `3`=1 WHERE `word`='festival';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `3`=2 WHERE `word`='We';";
mysqli_query($con,$query);
$var="worship";
$query = "INSERT INTO `list`(`word`,`3`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="Lord";
$query = "INSERT INTO `list`(`word`,`3`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="Ganesha";
$query = "INSERT INTO `list`(`word`,`3`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `3`=1 WHERE `word`='and';";
mysqli_query($con,$query);
$var="Goddess";
$query = "INSERT INTO `list`(`word`,`3`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="Lakshmi";
$query = "INSERT INTO `list`(`word`,`3`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `3`=1 WHERE `word`='It';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `3`=1 WHERE `word`='is';";
mysqli_query($con,$query);
$var="one";
$query = "INSERT INTO `list`(`word`,`3`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `3`=2  WHERE `word`='of';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `3`=1  WHERE `word`='the';";
mysqli_query($con,$query);
$var="biggest";
$query = "INSERT INTO `list`(`word`,`3`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `3`=2  WHERE `word`='festival';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `3`=1  WHERE `word`='celebrated';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `3`=1  WHERE `word`='in';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `3`=1  WHERE `word`='India';";
mysqli_query($con,$query);



$var="People";
$query = "INSERT INTO `list`(`word`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="worship";
$query = "INSERT INTO `list`(`word`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `4`=1 WHERE `word`='Goddess';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `4`=1 WHERE `word`='Lakshmi';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `4`=1 WHERE `word`='on';";
mysqli_query($con,$query);
$var="this";
$query = "INSERT INTO `list`(`word`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="day";
$query = "INSERT INTO `list`(`word`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `4`=1 WHERE `word`='the';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `4`=2 WHERE `word`='Goddess';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `4`=1 WHERE `word`='of';";
mysqli_query($con,$query);
$var="wealth";
$query = "INSERT INTO `list`(`word`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `4`=1 WHERE `word`='and';";
mysqli_query($con,$query);
$var="prosperity";
$query = "INSERT INTO `list`(`word`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `4`=1 WHERE `word`='in';";
mysqli_query($con,$query);
$var="our";
$query = "INSERT INTO `list`(`word`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="lives";
$query = "INSERT INTO `list`(`word`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `4`=2 WHERE `word`='People';";
mysqli_query($con,$query);
$var="decorates";
$query = "INSERT INTO `list`(`word`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="their";
$query = "INSERT INTO `list`(`word`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="houses";
$query = "INSERT INTO `list`(`word`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="with";
$query = "INSERT INTO `list`(`word`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="lamps";
$query = "INSERT INTO `list`(`word`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `4`=1 WHERE `word`='on';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `4`=1 WHERE `word`='Diwali';";
mysqli_query($con,$query);



$query = "UPDATE `list` SET `5`=1 WHERE `word`='Diwali';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `5`=1 WHERE `word`='is';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `5`=1 WHERE `word`='the';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `5`=1 WHERE `word`='festival';";
mysqli_query($con,$query);
$var="to";
$query = "INSERT INTO `list`(`word`,`5`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `5`=1 WHERE `word`='celebrate';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `5`=2 WHERE `word`='the';";
mysqli_query($con,$query);
$var="victory";
$query = "INSERT INTO `list`(`word`,`5`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `5`=1 WHERE `word`='of';";
mysqli_query($con,$query);
$var="truth";
$query = "INSERT INTO `list`(`word`,`5`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `5`=1 WHERE `word`='and';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `5`=1 WHERE `word`='People';";
mysqli_query($con,$query);
$var="invities";
$query = "INSERT INTO `list`(`word`,`5`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `5`=1 WHERE `word`='families';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `5`=2 WHERE `word`='and';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `5`=1 WHERE `word`='friends';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `5`=1 WHERE `word`='on';";
mysqli_query($con,$query);
$var="dinner";
$query = "INSERT INTO `list`(`word`,`5`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `5`=2 WHERE `word`='on';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `5`=2 WHERE `word`='Diwali';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `5`=2 WHERE `word`='the';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `5`=2 WHERE `word`='People';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `5`=1 WHERE `word`='in';";
mysqli_query($con,$query);
$var="Ayodhya";
$query = "INSERT INTO `list`(`word`,`5`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="welcomed";
$query = "INSERT INTO `list`(`word`,`5`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="their";
$query = "INSERT INTO `list`(`word`,`5`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="God";
$query = "INSERT INTO `list`(`word`,`5`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `5`=3 WHERE `word`='and';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `5`=2 WHERE `word`='celebrated';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `5`=3 WHERE `word`='on';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `5`=2 WHERE `word`='the';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `5`=2 WHERE `word`='People';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `5`=1 WHERE `word`='this';";
mysqli_query($con,$query);
$var="day";
$query = "INSERT INTO `list`(`word`,`5`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `5`=1 WHERE `word`='as';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `5`=2 WHERE `word`='festival';";
mysqli_query($con,$query);

header("Location:display.php");?>
